In [92]:
import pandas as pd
df=pd.read_csv('/content/loan.csv')

In [93]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [94]:
df.drop('Loan_ID',axis=1)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [95]:
df.dropna(inplace=True)

In [96]:
x=df.drop(['Loan_Status','Loan_ID'],axis=1)
y=df['Loan_Status']

In [97]:
x['Dependents'] = x['Dependents'].replace('3+', 3)

In [98]:
x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban

In [99]:
y.head()

1    N
2    Y
3    Y
4    Y
5    Y
Name: Loan_Status, dtype: object

In [100]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [110]:
x_train.shape

(384, 11)

In [111]:
y_train.shape

(384,)

In [112]:
x_test.shape

(96, 11)

In [113]:
y_test.shape

(96,)

In [101]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [102]:
le=OrdinalEncoder()
y=le.fit_transform(y.values.reshape(-1,1))

In [103]:
categorical_cols=['Gender','Married','Education','Self_Employed','Property_Area']
numerical_cols=['Dependents','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History']

In [104]:
ct = ColumnTransformer(
    transformers=[
        ('onehot',OrdinalEncoder(), categorical_cols),
        ('scaler', StandardScaler(), numerical_cols)
    ]
)

In [105]:
x_train_transformed = ct.fit_transform(x_train)
x_test_transformed = ct.transform(x_test)

In [114]:
x_train_transformed

array([[ 1.        ,  1.        ,  1.        , ..., -0.80993454,
        -2.39757504,  0.42607331],
       [ 0.        ,  0.        ,  0.        , ..., -0.3702096 ,
         0.28034473,  0.42607331],
       [ 1.        ,  1.        ,  1.        , ...,  0.17298003,
         0.28034473,  0.42607331],
       ...,
       [ 1.        ,  1.        ,  0.        , ..., -0.1762133 ,
         0.28034473,  0.42607331],
       [ 1.        ,  1.        ,  0.        , ...,  0.23764546,
         0.28034473,  0.42607331],
       [ 1.        ,  1.        ,  0.        , ..., -0.71940293,
         0.28034473,  0.42607331]])

In [115]:
y_train

172    N
288    Y
607    Y
55     Y
461    Y
      ..
141    Y
350    Y
445    Y
558    Y
137    Y
Name: Loan_Status, Length: 384, dtype: object

In [116]:
x_test_transformed

array([[ 1.        ,  1.        ,  1.        , ..., -0.80993454,
         0.28034473,  0.42607331],
       [ 1.        ,  0.        ,  1.        , ..., -0.1762133 ,
         0.28034473,  0.42607331],
       [ 1.        ,  1.        ,  0.        , ...,  1.28522547,
         0.28034473,  0.42607331],
       ...,
       [ 1.        ,  1.        ,  0.        , ..., -0.5642059 ,
         0.28034473,  0.42607331],
       [ 1.        ,  1.        ,  0.        , ..., -0.38314269,
         0.28034473,  0.42607331],
       [ 1.        ,  0.        ,  0.        , ..., -0.47367429,
         0.28034473,  0.42607331]])

In [117]:
y_test

92     Y
529    Y
505    Y
358    N
512    Y
      ..
281    Y
299    N
522    Y
33     Y
537    Y
Name: Loan_Status, Length: 96, dtype: object

In [118]:
import numpy as np

np.save("x_train_scaled.npy", x_train)
np.save("x_test_scaled.npy", x_test)
np.save("y_train.npy", y_train)
np.save("y_test.npy", y_test)

In [119]:
import joblib

joblib.dump(ct, "column_transformer.pkl")

['column_transformer.pkl']